export const listaEmociones = [
    // --- BLOQUE 1: CHILD INTERIOR (Completos 1-8) ---
    { audio: "https://arrobaverso.bandcamp.com/track/001-surrender-to-your-being", podcast: "https://open.spotify.com/episode/2qUYqWPu9f9gnKazqh5byW", playlist: "https://open.spotify.com/playlist/69FWFiqbM62vBhRcrW33BU" },
    { audio: "https://arrobaverso.bandcamp.com/track/002-inner-child", podcast: "https://open.spotify.com/episode/0lGsmBfBj4GYWRYTecX2AC", playlist: "https://open.spotify.com/playlist/3B2W5JZjk96L0KCdGvJUHm" },
    { audio: "https://arrobaverso.bandcamp.com/track/003-betrayal", podcast: "https://open.spotify.com/episode/3k8KsU734g7zhXciwQjMIS", playlist: "https://open.spotify.com/playlist/28KQw1QuPIjambEMLndfSd" },
    { audio: "https://arrobaverso.bandcamp.com/track/004-rejection", podcast: "https://open.spotify.com/episode/43QKyiNzlwllx8wRREeFnL", playlist: "https://open.spotify.com/playlist/0lTs2kUY5b0dGi9VidoQD1" },
    { audio: "https://arrobaverso.bandcamp.com/track/005-injustice", podcast: "https://open.spotify.com/episode/7cmor5vYxZRXWQDnClYYue", playlist: "https://open.spotify.com/playlist/7cYUKTqg5EysEQ2CydFn7d" },
    { audio: "https://arrobaverso.bandcamp.com/track/006-humiliation", podcast: "https://open.spotify.com/episode/1DCkB3yjwb2qZYkBewW42E", playlist: "https://open.spotify.com/playlist/0QsAGEtK2gWQ62R7FN2UxV" },
    { audio: "https://arrobaverso.bandcamp.com/track/007-abandonment", podcast: "https://open.spotify.com/episode/3pFQe5QqMK8n4dIMDDSp37", playlist: "https://open.spotify.com/playlist/2KB0eCnh2Yit5pQxJamvfV" },
    { audio: "https://arrobaverso.bandcamp.com/track/008-abuse", podcast: "https://open.spotify.com/episode/2U504AUjxv7NzGV8ctnRCQ", playlist: "https://open.spotify.com/playlist/3O0QMGaL5ePTMQYV6X8e8u" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/4UFH27Fr3v7Voz5tcXb0JR", playlist: "https://open.spotify.com/playlist/3Sxh1dB1WMxNbNuxR7njS2" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/3qL8YT8IZ361fdcxTrdtVG", playlist: "https://open.spotify.com/playlist/5iroslppZo3uj4N8Si7DqO" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/4ol1z3iNpmVBtPFhsng0iJ", playlist: "https://open.spotify.com/playlist/6qU21DIwJUksIkkniEf4Gw" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1CASlml1WEHbqA1AKxRyOA", playlist: "https://open.spotify.com/playlist/2K1IGA0p3mlE5c518l9ZhY" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1ahK2K0RR1mqYEgQxBTcRQ", playlist: "https://open.spotify.com/playlist/4KtUAxBrkTsy85p1XED6v8" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1gp1bts8sCfzZjkOtSMLUI", playlist: "https://open.spotify.com/playlist/3OYsFhGidxd2tpyTYnVJcV" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/6Xg4CA2cL1HEeoCcHXiyLL", playlist: "https://open.spotify.com/playlist/1wZc9x0t4KKD1iZ4XPPHF7" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/5qD570ddlxRgYSiOdM9N11", playlist: "https://open.spotify.com/playlist/27r9ZORZoF6WGt42jyruWW" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/3eFe629dSa4twvnCJO2UXh", playlist: "https://open.spotify.com/playlist/2xOB5QOSplGOKcwt2O4KpM" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0I2yLhiE5UXFSt9C1eUfH0", playlist: "https://open.spotify.com/playlist/1LQ4EVFFAfGcK7G5k0RIwf" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/3UZFUCWTl4JeO16Yl8fehy", playlist: "https://open.spotify.com/playlist/6EywMAsWZFZoLjVBJFvCIH" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/6p30trA4sv4aaUq3LjOaxG", playlist: "https://open.spotify.com/playlist/1ORVyljovDRYNIm8sKTcXy" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0V6SP63PpVIAr2J3jQwK1O", playlist: "https://open.spotify.com/playlist/4zvxgevkTlLoEfdleR6iHI" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0yhotz68wp3xFU6O4esZc1", playlist: "https://open.spotify.com/playlist/0cUSP9I2YyX5BgVUadMM2I" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1yHnY1hy2VjhLXbHzUmdAC", playlist: "https://open.spotify.com/playlist/0MlSghlI0aNuFI7ppOXe2A" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/5nMgF2wHGRggg4m6Lixb8F", playlist: "https://open.spotify.com/playlist/0jTZVLafHilc4zNjJgwbqe" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0yWzz4z875gHeCFIyhc4pW", playlist: "https://open.spotify.com/playlist/2Of47nfImTfTuv17FPK9zZ" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0kzBWecyQxgA5eB0GTn1eo", playlist: "https://open.spotify.com/playlist/2nsku3nc2lz5dgHc8nVCER" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/3JGxcEl7flSELnYUqaXD6J", playlist: "https://open.spotify.com/playlist/1D66LpbA8RpZ8ZpWKA51fi" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/0Zxok3JgVdfJDbjHXANhrN", playlist: "https://open.spotify.com/playlist/4Yzh41rUEp4JoMGPeCTxJi" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/2xbZHfzFONWwus8bVt0Nw6", playlist: "https://open.spotify.com/playlist/5PSEmalJPwRjYDMLuKfvgs" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1Ofy4WS35PuAtJNnQkeaHn", playlist: "https://open.spotify.com/playlist/5MmIynXom8hTjGoR5GsFeF" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/2kq4qbIjGg8vEo8JtUaUbl", playlist: "https://open.spotify.com/playlist/21lx28olW6pye566yuSFEr" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/1iocUjwSm6LVjqsP9tpNVZ", playlist: "https://open.spotify.com/playlist/4cZ5K9NtssmWGl3yyKi86j" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/286qAi8IDrlV42AWsEXE3y", playlist: "https://open.spotify.com/playlist/7zWm9HbDUd93ooaposg722" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/4uDoe8LrAQTp24tiHoXEFg", playlist: "https://open.spotify.com/playlist/2qEuvmgA75GwycGO3HIUK0" },
    { audio: "https://arrobaverso.bandcamp.com", podcast: "https://open.spotify.com/episode/2q4AG29XsHYqZR69fuec8e", playlist: "https://open.spotify.com/playlist/1ic2R7cwlhxkAhpk7cJr8E" }
];

